# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test module
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Build & Test module (cross compilation)
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
  workflow_call:
jobs:
  build_and_test_cross_compilation:
    strategy:
      fail-fast: false
      matrix:
        bazel-config: ["x86_64-linux", "aarch64-linux"]
    runs-on: ubuntu-24.04
    steps:
      - uses: eclipse-score/more-disk-space@v1
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Create Bazel output base directory
        run: |
          sudo mkdir -p /mnt/.bazel
          sudo chown -R $USER:$USER /mnt/.bazel
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          output-base: /mnt/.bazel
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}-${{ matrix.bazel-config }}
          repository-cache: true
          # Cache external/
          external-cache: true
      - name: Allow linux-sandbox
        uses: ./.github/actions/unblock_user_namespace_for_linux_sandbox
      - run: df -h
      - name: Bazel build targets
        # TODO: build all targets ( //... ) once python toolchain issue is resolved.
        run: |
          bazel build --config ${{ matrix.bazel-config }} //src/... //tests/... //examples/...
      - run: df -h
        if: always()
        # TODO Run tests on QEMU
